### ISSUE TITLE
Is the project dead?

### ISSUE THREAD

**Issue by kikismalls** [securitymagick/DVHHIOT#1]
Any updates?

**Comment by securitymagick** [comment]
The web application will be updated later this year (August / September).   Been very busy this summer. Not 100% sure what the updates will entail most likely some html5 specific vulnerabilities, possibly a nodejs chat web service (with more web service vulnerabilities) for group therapy with doctor Eliza.    

If there is something not working I can try to address that now if you can tell me what is wrong.
